version: 2.1

orbs:
  windows: circleci/windows@5.0.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:af:a4:23:5c:4a:01:5c:19:1f:50:73:9f:e2:85:5b"
      - checkout
      - run:
          name: version
          command: dotnet --version
      - run:
          name: check-cer
          command: winget install Microsoft.DotNet.SDK.8
      # - run:
      #     name: trust
      #     command: dotnet dev-certs https --trust
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:af:a4:23:5c:4a:01:5c:19:1f:50:73:9f:e2:85:5b"
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test